spring:  
  application:
    name: customer-service
    
server:
  port: ${PORT:8092}
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
      
management:
  security:
    enabled: false
  port: 8092