spring:  
  application:
    name: order-service
    
server:
  port: ${PORT:8090}
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  security:
    enabled: false
  port: 8090